# Generated by Django 3.0.8 on 2020-07-30 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('date', 'time')},
        ),
    ]
