# Generated by Django 3.0.8 on 2020-07-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200730_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='time',
            field=models.CharField(choices=[('1', '10:00am - 10:15am'), ('2', '10:15am - 10:30am'), ('3', '10:30am - 10:45am'), ('4', '10:45am - 11:00am'), ('5', '11:00am - 11:15am'), ('6', '11:15am - 11:30am'), ('7', '11:30am - 11:45am'), ('8', '11:45am - 12:00pm'), ('9', '12:00pm - 12:15pm'), ('10', '12:15pm - 12:30pm'), ('11', '12:30pm - 12:45pm'), ('12', '12:45pm - 1:00pm'), ('13', '1:00pm - 1:15pm'), ('14', '1:15pm - 1:30pm'), ('15', '1:30pm - 1:45pm'), ('16', '1:45pm - 2:00pm'), ('17', '2:00pm - 2:15pm'), ('18', '2:15pm - 2:30pm'), ('19', '2:30pm - 2:45pm'), ('20', '2:45pm - 3:00pm')], default='1', max_length=2),
        ),
    ]
